/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.ComidaData;
import Entidades.Comida;
import java.awt.Color;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cristina
 */
public class FormularioGestionComidas extends javax.swing.JInternalFrame {

    ArrayList<Comida> listaC;
    ComidaData cd;
    DefaultTableModel modelo = new DefaultTableModel();
    int id;
    int calorias;

    public FormularioGestionComidas() {
        listaC = new ArrayList();
        cd = new ComidaData();
        initComponents();
        armarCabecera();
        // cargarComidas();
        if(!jRadioTodas.isSelected()&&!jRadioMenos.isSelected()){
            jBModificar.setEnabled(false);
            jBEliminar.setEnabled(false);
        }
        this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jBEliminar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTCalorias = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioTodas = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioMenos = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png"))); // NOI18N
        jBEliminar.setEnabled(false);
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 50, -1));

        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editar.png"))); // NOI18N
        jBModificar.setEnabled(false);
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 309, 187));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Comidas disponibles:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jTCalorias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTCaloriasKeyReleased(evt);
            }
        });
        getContentPane().add(jTCalorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 61, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Mostrar todas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jRadioTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTodasActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioTodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Menos de ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Kcal");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jRadioMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMenosActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Administracion de comidas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        int fila = jTable.getSelectedRow();
        if(fila!=-1){
        int idComida = (Integer) jTable.getValueAt(fila, 0);

        cd.eliminarComida(idComida);
        }
        borrarFilas();

    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        
        int fila = jTable.getSelectedRow();
        if (fila != -1) {
            if (jTable.getValueAt(fila, 0) instanceof String) {
                id = Integer.parseInt((String) jTable.getValueAt(fila, 0));
            } else {
                id = (Integer) jTable.getValueAt(fila, 0);
            }
            String nombre = (String) jTable.getValueAt(fila, 1);
            String detalle = (String) jTable.getValueAt(fila, 2);
            if (jTable.getValueAt(fila, 3) instanceof String) {
                calorias = Integer.parseInt((String) jTable.getValueAt(fila, 3));
            } else {
                calorias = (Integer) jTable.getValueAt(fila, 3);
            }
            Comida c1 = new Comida(id, calorias, nombre, detalle, true);
            cd.modificarComida(c1);
            System.out.println(cd);
            borrarFilas();
            cargarComidas();
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jRadioTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTodasActionPerformed
        borrarFilas();
        jRadioMenos.setSelected(false);
        if(jRadioTodas.isSelected()){
        cargarComidas();
        jBEliminar.setEnabled(true);
        jBModificar.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioTodasActionPerformed

    private void jRadioMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMenosActionPerformed
        borrarFilas();
        jRadioTodas.setSelected(false);
        if(jRadioMenos.isSelected()){
         jBEliminar.setEnabled(true);
        jBModificar.setEnabled(true); 
        
        }
        
        
    }//GEN-LAST:event_jRadioMenosActionPerformed

    private void jTCaloriasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCaloriasKeyReleased
        borrarFilas();
        
        try{    
            if(jRadioMenos.isSelected()){
        int calorias=Integer.parseInt(jTCalorias.getText());
        for (Comida c :cd.buscarPorCalorias(calorias) ) {
            
            modelo.addRow(new Object[]{c.getIdComida(), c.getNombre(), c.getDetalle(), c.getCantCalorias(), c.isEstado()});
        
        }
}}catch (NumberFormatException ex){
    JOptionPane.showMessageDialog(null, "Debe ingresar las calorias en formato numerico");
    jTCalorias.setText("");
}
        
    }//GEN-LAST:event_jTCaloriasKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioMenos;
    private javax.swing.JRadioButton jRadioTodas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCalorias;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        ArrayList<Object> lista = new ArrayList<>();
        lista.add("IDComida");
        lista.add("Nombre");
        lista.add("Detalle");
        lista.add("Calorias");
        for (Object item : lista) {
            modelo.addColumn(item);
        }
        
        jTable.setModel(modelo);
       

    }
   

    private void borrarFilas() {
        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    private void cargarComidas() {
        borrarFilas();
        listaC = (ArrayList) cd.listarComidas();
        for (Comida c : listaC) {
            System.out.println(c);
            modelo.addRow(new Object[]{c.getIdComida(), c.getNombre(), c.getDetalle(), c.getCantCalorias(), c.isEstado()});

        }
       
    }

}
