/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.ComidaData;
import AccesoADatos.DietaComidaData;
import AccesoADatos.DietaData;
import AccesoADatos.PacienteData;
import Entidades.Comida;
import Entidades.Dieta;
import Entidades.DietaComida;
import Entidades.Paciente;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgar
 */
public class HistorialPaciente extends javax.swing.JInternalFrame {
    private Paciente paciente = null;
    private Dieta dieta = null;
    private PacienteData paData= new PacienteData();
    private DietaData dieData = new DietaData();
    private DietaComidaData dcd = new DietaComidaData();
    private ComidaData cd=new ComidaData();
    private ArrayList <Comida> listaC;
    private DefaultTableModel modelo;
    /**
     * Creates new form HistorialPaciente
     */
    public HistorialPaciente() {
        initComponents();
        paData= new PacienteData();
        dieData = new DietaData();
        dcd = new DietaComidaData();
        modelo = new DefaultTableModel();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPHistorial = new javax.swing.JPanel();
        jPTitulo1 = new javax.swing.JPanel();
        jLTitulo1 = new javax.swing.JLabel();
        jLDocumento1 = new javax.swing.JLabel();
        jTDocumento = new javax.swing.JTextField();
        jLNombre1 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLApellido1 = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();
        jLDomicilio1 = new javax.swing.JLabel();
        jTDomicilio = new javax.swing.JTextField();
        jLTelefono1 = new javax.swing.JLabel();
        jTTelefono = new javax.swing.JTextField();
        jBBuscar1 = new javax.swing.JButton();
        jPSeparador = new javax.swing.JPanel();
        jLDieta1 = new javax.swing.JLabel();
        jTDieta = new javax.swing.JTextField();
        jLInicio1 = new javax.swing.JLabel();
        jLFinal1 = new javax.swing.JLabel();
        jLInicial1 = new javax.swing.JLabel();
        jTInicial = new javax.swing.JTextField();
        jLActual1 = new javax.swing.JLabel();
        jTActual = new javax.swing.JTextField();
        jLBuscado1 = new javax.swing.JLabel();
        jTBuscado = new javax.swing.JTextField();
        jBEliminar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioDisponible = new javax.swing.JRadioButton();
        jRAsignadas = new javax.swing.JRadioButton();
        jBAgregar = new javax.swing.JButton();
        jBEliminarComida = new javax.swing.JButton();
        jDInicio = new com.toedter.calendar.JDateChooser();
        jDFinal = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPHistorial.setBackground(new java.awt.Color(255, 255, 255));

        jPTitulo1.setBackground(new java.awt.Color(102, 255, 255));

        jLTitulo1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLTitulo1.setText("Historial Paciente");

        javax.swing.GroupLayout jPTitulo1Layout = new javax.swing.GroupLayout(jPTitulo1);
        jPTitulo1.setLayout(jPTitulo1Layout);
        jPTitulo1Layout.setHorizontalGroup(
            jPTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTitulo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTitulo1)
                .addGap(359, 359, 359))
        );
        jPTitulo1Layout.setVerticalGroup(
            jPTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTitulo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLDocumento1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLDocumento1.setText("Documento:");

        jTDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDocumentoActionPerformed(evt);
            }
        });
        jTDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTDocumentoKeyReleased(evt);
            }
        });

        jLNombre1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLNombre1.setText("Nombre:");

        jTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTNombreKeyReleased(evt);
            }
        });

        jLApellido1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLApellido1.setText("Apellido:");

        jTApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTApellidoKeyReleased(evt);
            }
        });

        jLDomicilio1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLDomicilio1.setText("Domicilio:");

        jTDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTDomicilioKeyReleased(evt);
            }
        });

        jLTelefono1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLTelefono1.setText("Telefono:");

        jTTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTTelefonoKeyReleased(evt);
            }
        });

        jBBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar 24.png"))); // NOI18N
        jBBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscar1ActionPerformed(evt);
            }
        });

        jPSeparador.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPSeparadorLayout = new javax.swing.GroupLayout(jPSeparador);
        jPSeparador.setLayout(jPSeparadorLayout);
        jPSeparadorLayout.setHorizontalGroup(
            jPSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPSeparadorLayout.setVerticalGroup(
            jPSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLDieta1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLDieta1.setText("Nombre Dieta:");

        jTDieta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTDietaKeyReleased(evt);
            }
        });

        jLInicio1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLInicio1.setText("Fecha Inicio:");

        jLFinal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLFinal1.setText("Fecha Final:");

        jLInicial1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLInicial1.setText("Peso Inicial:");

        jTInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTInicialKeyReleased(evt);
            }
        });

        jLActual1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLActual1.setText("Peso Actual: ");

        jTActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTActualActionPerformed(evt);
            }
        });
        jTActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTActualKeyReleased(evt);
            }
        });

        jLBuscado1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLBuscado1.setText("Peso Buscado:");

        jTBuscado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBuscadoKeyReleased(evt);
            }
        });

        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png"))); // NOI18N
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editar.png"))); // NOI18N
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Comida", "Nombre", "Detalle", "Calorias"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jRadioDisponible.setText("Comidas Disponibles");
        jRadioDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDisponibleActionPerformed(evt);
            }
        });

        jRAsignadas.setText("Comidas asignadas");

        jBAgregar.setText("Agregar Comida");
        jBAgregar.setEnabled(false);
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBEliminarComida.setText("Eliminar Comida");
        jBEliminarComida.setEnabled(false);

        javax.swing.GroupLayout jPHistorialLayout = new javax.swing.GroupLayout(jPHistorial);
        jPHistorial.setLayout(jPHistorialLayout);
        jPHistorialLayout.setHorizontalGroup(
            jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPSeparador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPHistorialLayout.createSequentialGroup()
                .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPHistorialLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDocumento1)
                            .addComponent(jLDomicilio1))
                        .addGap(18, 18, 18)
                        .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTDomicilio))
                        .addGap(33, 33, 33)
                        .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPHistorialLayout.createSequentialGroup()
                                .addComponent(jLNombre1)
                                .addGap(18, 18, 18)
                                .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPHistorialLayout.createSequentialGroup()
                                .addComponent(jLTelefono1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTTelefono)))
                        .addGap(33, 33, 33)
                        .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBBuscar1)
                            .addComponent(jLApellido1))
                        .addGap(18, 18, 18)
                        .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPHistorialLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPHistorialLayout.createSequentialGroup()
                                .addComponent(jBEliminar)
                                .addGap(16, 16, 16))
                            .addGroup(jPHistorialLayout.createSequentialGroup()
                                .addComponent(jLInicial1)
                                .addGap(18, 18, 18)
                                .addComponent(jTInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLActual1)
                                .addGap(18, 18, 18)
                                .addComponent(jTActual, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLBuscado1))
                            .addGroup(jPHistorialLayout.createSequentialGroup()
                                .addComponent(jLDieta1)
                                .addGap(18, 18, 18)
                                .addComponent(jTDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLInicio1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLFinal1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTBuscado, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jBModificar)
                            .addComponent(jDFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPHistorialLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioDisponible)
                            .addComponent(jRAsignadas))
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBAgregar)
                            .addComponent(jBEliminarComida))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPHistorialLayout.setVerticalGroup(
            jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHistorialLayout.createSequentialGroup()
                .addComponent(jPTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDocumento1)
                    .addComponent(jTDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombre1)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLApellido1)
                    .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPHistorialLayout.createSequentialGroup()
                        .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLDomicilio1)
                                .addComponent(jTDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLTelefono1))
                            .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPHistorialLayout.createSequentialGroup()
                        .addComponent(jBBuscar1)
                        .addGap(18, 18, 18)))
                .addComponent(jPSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPHistorialLayout.createSequentialGroup()
                        .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLDieta1)
                                .addComponent(jTDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLInicio1))
                            .addComponent(jLFinal1)
                            .addComponent(jDInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLInicial1)
                                .addComponent(jLActual1)
                                .addComponent(jTActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLBuscado1)
                                .addComponent(jTBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBEliminar)
                            .addComponent(jBModificar))
                        .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPHistorialLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jRadioDisponible)
                                .addGap(63, 63, 63)
                                .addComponent(jRAsignadas))
                            .addGroup(jPHistorialLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPHistorialLayout.createSequentialGroup()
                                        .addComponent(jBAgregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                        .addComponent(jBEliminarComida)
                                        .addGap(98, 98, 98))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPHistorialLayout.createSequentialGroup()
                        .addComponent(jDFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jBModificar.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDocumentoActionPerformed

    private void jBBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscar1ActionPerformed
        // TODO add your handling code here:
         try{
            Integer dni = Integer.parseInt(jTDocumento.getText());
            paciente=paData.buscarPorDocumento(dni);
            if(paciente != null){
                dieta=dieData.buscarDietaPorIDPaciente(paciente.getIdPaciente());
               
                if(dieta != null){
                    
                    this.jTNombre.setText(paciente.getNombre());
                    this.jTApellido.setText(paciente.getApellido());
                    this.jTDomicilio.setText(paciente.getDomicilio());
                    this.jTTelefono.setText(Integer.toString(paciente.getTelefono()));
                    this.jTDieta.setText(dieta.getNombre());
                    
                    LocalDate lc= dieta.getFechaInicio();
                    Date date=java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
                    jDInicio.setDate(date);
                    lc= dieta.getFechaFinal();
                    date=java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
                    jDFinal.setDate(date);
                    this.jTInicial.setText(Double.toString( dieta.getPesoInicial()));
                    this.jTActual.setText(Double.toString( dieta.getPesoActual()));
                    this.jTBuscado.setText(Double.toString(dieta.getPesoBuscado()));
                }  
            }else{
                JOptionPane.showMessageDialog(null, "El paciente no exite");
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Debe ingresar un numero valido");
        }
    }//GEN-LAST:event_jBBuscar1ActionPerformed

    private void jTActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTActualActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        if(paciente!= null && dieta!=null){
            paData.eliminarPaciente(paciente.getIdPaciente());
            dieData.eliminarDieta(dieta.getIdDieta());
            paciente=null;
            dieta=null;
            limpiarCampos();
        }
        else{
            JOptionPane.showMessageDialog(null, "No hay paciente ni dieta seleccionado");
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
         try{
            if(paciente !=null && dieta != null){
                paciente.setDni(Integer.parseInt(this.jTDocumento.getText()));
                paciente.setNombre(this.jTNombre.getText());
                paciente.setApellido(this.jTApellido.getText());
                paciente.setDomicilio(this.jTDomicilio.getText());
                paciente.setTelefono(Integer.parseInt(this.jTTelefono.getText()));
                dieta.setNombre(this.jTDieta.getText());
                Date fecha=this.jDInicio.getDate();
                LocalDate  fechaInicio=fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                dieta.setFechaInicio(fechaInicio);
                fecha=this.jDFinal.getDate();
                LocalDate fechaFinal=fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                dieta.setFechaFinal(fechaFinal);
                dieta.setPesoInicial(Double.parseDouble(this.jTInicial.getText()));
                dieta.setPesoActual(Double.parseDouble(this.jTBuscado.getText()));
                dieta.setPesoBuscado(Double.parseDouble(this.jTBuscado.getText()));
                paData.modificarPaciente(paciente);
                dieData.modificarDieta(dieta);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Debe ingresar un numero valido" +ex.getMessage());
        }
        limpiarCampos(); 
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jTDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDocumentoKeyReleased
        // TODO add your handling code here:
        Pattern patron=Pattern.compile("[0-9]+");
       String nro = this.jTDocumento.getText();
       Matcher m= patron.matcher(nro);
       if(!m.matches() && nro.length()>0){
           JOptionPane.showMessageDialog(this, "No es un numero");
           this.jTDocumento.setText(nro.substring(0, nro.length()-1));
           this.jTDocumento.requestFocus();
       }
    }//GEN-LAST:event_jTDocumentoKeyReleased

    private void jTNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreKeyReleased
        // TODO add your handling code here:
        Pattern patron=Pattern.compile("[a-zA-Z_ \\t\\n\\x0B\\f\\r]+");
       String nro = this.jTNombre.getText();
       Matcher m= patron.matcher(nro);
       if(!m.matches() && nro.length()>0){
           JOptionPane.showMessageDialog(this, "No es una letra");
           this.jTNombre.setText(nro.substring(0, nro.length()-1));
           this.jTNombre.requestFocus();
       }
    }//GEN-LAST:event_jTNombreKeyReleased

    private void jTApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTApellidoKeyReleased
        // TODO add your handling code here:
        Pattern patron=Pattern.compile("[a-zA-Z_ \\t\\n\\x0B\\f\\r]+");
       String nro = this.jTApellido.getText();
       Matcher m= patron.matcher(nro);
       if(!m.matches() && nro.length()>0){
           JOptionPane.showMessageDialog(this, "No es una letra");
           this.jTApellido.setText(nro.substring(0, nro.length()-1));
           this.jTApellido.requestFocus();
       }
    }//GEN-LAST:event_jTApellidoKeyReleased

    private void jTDomicilioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDomicilioKeyReleased
        // TODO add your handling code here:
        Pattern patron=Pattern.compile("[a-zA-Z_0-9_ \\t\\n\\x0B\\f\\r]+");
       String nro = this.jTDomicilio.getText();
       Matcher m= patron.matcher(nro);
       if(!m.matches() && nro.length()>0){
           JOptionPane.showMessageDialog(this, "No es una letra");
           this.jTDomicilio.setText(nro.substring(0, nro.length()-1));
           this.jTDomicilio.requestFocus();
       }
    }//GEN-LAST:event_jTDomicilioKeyReleased

    private void jTTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTelefonoKeyReleased
        // TODO add your handling code here:
        Pattern patron=Pattern.compile("[0-9]+");
       String nro = this.jTTelefono.getText();
       Matcher m= patron.matcher(nro);
       if(!m.matches() && nro.length()>0){
           JOptionPane.showMessageDialog(this, "No es un numero");
           this.jTTelefono.setText(nro.substring(0, nro.length()-1));
           this.jTTelefono.requestFocus();
       }
    }//GEN-LAST:event_jTTelefonoKeyReleased

    private void jTDietaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDietaKeyReleased
        // TODO add your handling code here:
        Pattern patron=Pattern.compile("[a-zA-Z_ \\t\\n\\x0B\\f\\r]+");
       String nro = this.jTDieta.getText();
       Matcher m= patron.matcher(nro);
       if(!m.matches() && nro.length()>0){
           JOptionPane.showMessageDialog(this, "No es una letra");
           this.jTDieta.setText(nro.substring(0, nro.length()-1));
           this.jTDieta.requestFocus();
       }
    }//GEN-LAST:event_jTDietaKeyReleased

    private void jTInicialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTInicialKeyReleased
        // TODO add your handling code here:
         Pattern patron=Pattern.compile("[0-9_.]+");
       String nro = this.jTInicial.getText();
       Matcher m= patron.matcher(nro);
       if(!m.matches() && nro.length()>0){
           JOptionPane.showMessageDialog(this, "No es un numero");
           this.jTInicial.setText(nro.substring(0, nro.length()-1));
           this.jTInicial.requestFocus();
       }
    }//GEN-LAST:event_jTInicialKeyReleased

    private void jTActualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTActualKeyReleased
        // TODO add your handling code here:
        Pattern patron=Pattern.compile("[0-9_.]+");
       String nro = this.jTActual.getText();
       Matcher m= patron.matcher(nro);
       if(!m.matches() && nro.length()>0){
           JOptionPane.showMessageDialog(this, "No es un numero");
           this.jTActual.setText(nro.substring(0, nro.length()-1));
           this.jTActual.requestFocus();
       }
    }//GEN-LAST:event_jTActualKeyReleased

    private void jTBuscadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscadoKeyReleased
        // TODO add your handling code here:
        Pattern patron=Pattern.compile("[0-9_.]+");
       String nro = this.jTBuscado.getText();
       Matcher m= patron.matcher(nro);
       if(!m.matches() && nro.length()>0){
           JOptionPane.showMessageDialog(this, "No es un numero");
           this.jTBuscado.setText(nro.substring(0, nro.length()-1));
           this.jTBuscado.requestFocus();
       }
    }//GEN-LAST:event_jTBuscadoKeyReleased

    private void jRadioDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDisponibleActionPerformed
       limpiarCampos();
        
        jBAgregar.setEnabled(true);
       jBEliminarComida.setEnabled(false);
       jRAsignadas.setSelected(false);
       listarComidas();
    }//GEN-LAST:event_jRadioDisponibleActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        int fila=jTable1.getSelectedRow();
       if(fila!=-1){
           // ArrayList<Integer> listaC=new ArrayList();
            Comida c1=cd.buscarComidaPorId((Integer)jTable1.getValueAt(fila, 0));
            int idComida= (Integer)jTable1.getValueAt(fila, 0);
            System.out.println(idComida);
            System.out.println("idDieta "+dieta.getIdDieta());
            //listaC.add(c1.getIdComida());
            Dieta d1=dieData.buscarDietaPorID(dieta.getIdDieta());
            DietaComida dc1=new DietaComida(d1, c1);
            dcd.agregarComidaAUnaDieta(c1.getIdComida(),d1.getIdDieta() );
        }
    //int idDieta=obtenerDieta();
    //List<Integer> idComidas=obteneridComidas();
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void limpiarCampos(){
        this.jTDocumento.setText("");
        this.jTNombre.setText("");
        this.jTApellido.setText("");
        this.jTDomicilio.setText("");
        this.jTTelefono.setText("");
        this.jDInicio.setDate(new Date());
        this.jDFinal.setDate(new Date());
        this.jTDieta.setText("");
        this.jTInicial.setText("");
        this.jTActual.setText("");
        this.jTBuscado.setText("");
    }
    
    private void armarCabeceraTabla(){
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Id Comida");
        filaCabecera.add("Nombre");
        filaCabecera.add("Detalles");
        filaCabecera.add("Calorias");
        for(Object it: filaCabecera){
            modelo.addColumn(it);
        }
        jTable1.setModel(modelo);
    }
    
    private void borrarFilaTabla(){
        int indice = modelo.getRowCount() -1;
        for(int i = indice; i>=0; i--){
            modelo.removeRow(i);
        }
    }
    
    private void cargarDatosComida(){
        listaC = dcd.listarComidas(dieta.getIdDieta());
        System.out.println(dieta.getIdDieta() +dieta.getNombre());
        for(Comida c : listaC){
            System.out.println(c);
            modelo.addRow(new Object[] {c.getIdComida(), c.getNombre(), c.getDetalle(), c.getCantCalorias()});
        }
        
       
    }
    private void listarComidas(){
        listaC =  (ArrayList)cd.listarComidas();
        for (Comida c : listaC) {
            System.out.println(c);
            modelo.addRow(new Object[]{c.getIdComida(), c.getNombre(), c.getDetalle(), c.getCantCalorias(), c.isEstado()});

        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBuscar1;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBEliminarComida;
    private javax.swing.JButton jBModificar;
    private com.toedter.calendar.JDateChooser jDFinal;
    private com.toedter.calendar.JDateChooser jDInicio;
    private javax.swing.JLabel jLActual1;
    private javax.swing.JLabel jLApellido1;
    private javax.swing.JLabel jLBuscado1;
    private javax.swing.JLabel jLDieta1;
    private javax.swing.JLabel jLDocumento1;
    private javax.swing.JLabel jLDomicilio1;
    private javax.swing.JLabel jLFinal1;
    private javax.swing.JLabel jLInicial1;
    private javax.swing.JLabel jLInicio1;
    private javax.swing.JLabel jLNombre1;
    private javax.swing.JLabel jLTelefono1;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JPanel jPHistorial;
    private javax.swing.JPanel jPSeparador;
    private javax.swing.JPanel jPTitulo1;
    private javax.swing.JRadioButton jRAsignadas;
    private javax.swing.JRadioButton jRadioDisponible;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTActual;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTBuscado;
    private javax.swing.JTextField jTDieta;
    private javax.swing.JTextField jTDocumento;
    private javax.swing.JTextField jTDomicilio;
    private javax.swing.JTextField jTInicial;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTTelefono;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
